# Generated by Django 4.2.7 on 2023-11-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_tag_articles_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='ismain',
            new_name='is_main',
        ),
    ]
